### ISSUE TITLE
Is it possible to change the license?

### ISSUE THREAD

**Issue by ultimaweapon** [spicydog/ThaiTokenizer#2]
I would like to create a new npm package based on this project. The problem is this project licensed under GPL, which required any project that using it or derived from it also GPL too.

**Comment by spicydog** [comment]
Let's make it MIT then.
a3a012f4e9f77571d884994119fd021cc772b0db

**Comment by ultimaweapon** [comment]
Awesome!

**Comment by zymotik** [comment]
Thank you!

ขอบคุณมากครับ

**Comment by spicydog** [comment]
@ultimaweapon Please let me know when your package is publish.

I will refer the users to that package if they wish to use NPM.
